LearnSoftware/Areas/Information/Controllers/ForumMessagesController.cs
using System;
using System.Linq;
using LearnSoftware.Areas.Identity.Data;
using LearnSoftware.ViewModels.Forums;
using LearnSoftware.ViewModels.Messges;
using LearnSoftware.Controllers;
using LearnSoftware.Models;
using LearnSoftware.Models.Information;
using LearnSoftware.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using LearnSoftware.Services.Interfaces;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace LearnSoftware.Areas.Information.Controllers
{
    [Area("Information")]
    public class ForumMessagesController : Controller
    {
        private IForumMessageService forumMessageService;
        private IForumService forumService;
        private UserManager<LSIdentityUser> userManager;

        public ForumMessagesController(IForumMessageService forumMessageService, IForumService forumService, UserManager<LSIdentityUser> userManager)
        {
            this.forumMessageService = forumMessageService;
            this.forumService = forumService;
            this.userManager = userManager;
        }

        [Authorize]
        //[HttpGet("/ForumMessages/Edit/{forumMessageId}")]
        public IActionResult Edit(int forumMessageId, int page = 1)
        {
            var message = this.forumMessageService.GetForumMessage((int)forumMessageId);

            if(message == null)
            {
                return this.NotFound();
            }

            if(this.User.Identity.Name != message.User.UserName || !message.Forum.IsActive)
            {
                return this.Unauthorized();
            }

            var model = new MessageViewModel()
            {
                Id = message.Id,
                Message = message.Message,
                CurrentPage = page
            };

            return this.View(model);
        }

        [HttpPost]
        [Authorize]
        //[HttpPost("/ForumMessages/Edit/{forumMessageId}")]
        public IActionResult Edit(MessageViewModel model)
        {
            if(!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var message = this.forumMessageService.GetForumMessage(model.Id);

            if (message == null)
            {
                return this.NotFound();
            }

            if (this.User.Identity.Name != message.User.UserName || !message.Forum.IsActive)
            {
                return this.Unauthorized();
            }

            forumMessageService.UpdateMessage(message, model.Message);

            return this.RedirectToAction("Forum", "Forums", new { id = message.Forum.Id, page = model.CurrentPage });
        }

        [Authorize]
        [HttpPost]
        public IActionResult Create(ForumViewModel model)
        {
            if(!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var forum = forumService.GetForum(model.Id);
            var user = userManager.FindByNameAsync(this.User.Identity.Name).Result;

            if (forum == null || user == null)
            {
                return this.NotFound();
            }

            if(!forum.IsActive)
            {
                return this.Unauthorized();
            }

            forumMessageService.AddMessage(forum, user, model.NewComment);

            return this.RedirectToAction("Forum", "Forums", new { id = forum.Id, page = model.MaxPage });
        }
    }
}

LearnSoftware/Areas/Information/Controllers/ForumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using LearnSoftware.Areas.Identity.Data;
using LearnSoftware.ViewModels.ForumCategories;
using LearnSoftware.ViewModels.Forums;
using LearnSoftware.Controllers;
using LearnSoftware.Models;
using LearnSoftware.Models.Information;
using LearnSoftware.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using LearnSoftware.Services.Interfaces;

namespace LearnSoftware.Areas.Information.Controllers
{
    [Area("Information")]
    public class ForumsController : Controller
    {
        private IPageManager pageService;
        private IForumService forumService;
        private IForumCategoryService forumCategoryService;
        private IForumMessageService forumMessageService;
        private UserManager<LSIdentityUser> userManager;

        public ForumsController(IForumService forumService, IForumCategoryService forumCategoryService, IForumMessageService forumMessageService, UserManager<LSIdentityUser> userManager, IPageManager pageManager)
        {
            this.forumCategoryService = forumCategoryService;
            this.forumMessageService = forumMessageService;
            this.forumService = forumService;
            this.pageService = pageManager;
            this.userManager = userManager;
        }

        [Authorize]
        public IActionResult Index(int forumCategoryId, string search = null, int page = 1)
        {
            var forumCategory = forumCategoryService.GetForumCategory((int)forumCategoryId);

            if(forumCategory == null)
            {
                return this.NotFound();
            }

            var forums = forumService.GetForums(forumCategoryId, page, search)
                .Select(f => new FocumCategoryIndexForumViewModel()
                {
                    Id = f.Id,
                    Name = f.Name,
                    CreatedOn = f.CreationDate.ToString(),
                    CreatorUsername = f.Creator.UserName
                });

            var maxPage = pageService.GetMaxPage(forumService.GetCount(forumCategoryId));
            var minPage = pageService.GetMinPage(maxPage);

            ForumCategoryIndexViewModel model = new ForumCategoryIndexViewModel()
            {
                Id = (int)forumCategoryId,
                CurrentPage  = page,
                Search = search,
                MinPage = minPage,
                MaxPage = maxPage,
                Forums = forums.ToList(),
                ForumCategoryName = forumCategory.Name
            };

            return View(model);
        }

        [Authorize]
        public IActionResult RedirectToForum(int forumMessageId)
        {
            var message = forumMessageService.GetForumMessage((int)forumMessageId);

            if (message == null)
            {
                return this.NotFound();
            }

            return this.RedirectToAction("Forum", "Forums", new { id = message.Forum.Id });
        }

        [Authorize]
        [HttpGet("/Forums/Create/{forumCategoryId}")]
        public IActionResult Create(int forumCategoryId)
        {
            var hasForumCategory = forumCategoryService.HasForumCategory((int)forumCategoryId);

            if(!hasForumCategory)
            {
                return this.NotFound();
            }

            CreateForumViewModel model = new CreateForumViewModel() { Id = (int)forumCategoryId };

            return this.View(model);
        }

        [Authorize]
        [HttpPost("/Forums/Create/{forumCategoryId}")]
        public IActionResult Create(CreateForumViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return View(model);
            }

            var forumCategory = this.forumCategoryService.GetForumCategory(model.Id);

            if (forumCategory == null)
            {
                return this.NotFound();
            }

            var user = this.userManager.FindByNameAsync(this.User.Identity.Name).Result;

            if(user == null)
            {
                return this.NotFound();
            }

            int forumId = forumService.AddForum(user, forumCategory, model.Name, model.FirstComment);

            return this.RedirectToAction("Forum","Forums",new { id = forumId });
        }

        [Authorize]
        public IActionResult Forum(int id, int page = 1)
        {
            var forum = this.forumService.GetForum((int)id);

            if(forum == null)
            {
                return this.NotFound();
            }

            IEnumerable<ForumMessage> messages = forumMessageService.GetForumMessages(id, page)
                                                                    .OrderBy(m => m.CreationDate);
            var maxPage = pageService.GetMaxPage(forumMessageService.GetCount(id));
            var minPage = pageService.GetMinPage(maxPage);

            var model = new ForumViewModel()
            {
                Id = forum.Id,
                IsActive = forum.IsActive,
                CurrentPage = page,
                MinPage = minPage,
                MaxPage = maxPage,
                CreationDate = forum.CreationDate.ToString(),
                UpdateDate = forum.UpdateDate.ToString(),
                Name = forum.Name,
                CreatorUsername = forum.Creator.UserName,
                Messages = messages.Select(m => new ForumMessageViewModel()
                {
                    CommenterUsername = m.User.UserName,
                    CreationDate = m.CreationDate.ToString(),
                    UpdateDate = m.UpdateDate.ToString(),
                    Id = m.Id,
                    Message = m.Message
                }).ToList()
            };

            return this.View(model);
        }

        [Authorize]
        public IActionResult DeactivateForum(int forumId)
        {
            var forum = forumService.GetForum((int)forumId);

            if(forum == null)
            {
                return this.NotFound();
            }

            if(this.User.Identity.Name != forum.Creator.UserName)
            {
                return this.Unauthorized();
            }

            forumService.DeactivateForum(forum);

            return this.RedirectToAction("Forum", "Forums", new { id = forumId });
        }
    }
}

LearnSoftware/Areas/Information/Views/Forums/Create.cshtml
@{
    ViewData["Title"] = "Create Forum";
}

@using LearnSoftware.ViewModels.Forums
@model CreateForumViewModel

<hr />
<div class="col-sm-offset-3">
    @Html.ValidationSummary()
</div>
<form asp-area="Information" asp-controller="Forums" asp-action="Create" method="post">
    <div class="row center-items form-group">
        <div class="col-sm-offset-3 col-sm-6">
            <input type="hidden" asp-for="Id">
            <label for="Forum Name"></label>
            <input class="form-control" placeholder="Forum Name" type="text" asp-for="Name">
        </div>
    </div>
    <div class="row center-items form-group">
        <div class="col-sm-offset-3 col-sm-6">
            <label for="Comment"></label>
            <textarea class="form-control" rows="5" placeholder="Comment" asp-for="FirstComment"></textarea>
        </div>
    </div>
    <div class="row center-items form-group">
        <div class="col-sm-offset-3 col-sm-6">
            <input style="margin-top: 20px" class="form-control btn btn-primary" type="submit" value="Create Forum" />
        </div>
    </div>
</form>

LearnSoftware/Areas/Information/Views/Forums/Forum.cshtml
@using LearnSoftware.ViewModels.Forums
@model ForumViewModel

@{
    ViewData["Title"] = Model.Name;
}
<hr />

@if (this.User.Identity.Name == Model.CreatorUsername && Model.IsActive)
{
    <div class="row">
        <div class="col-sm-offset-5 col-sm-2">
            <a align="left" class="btn btn-primary" asp-area="Information" asp-controller="Forums" asp-action="DeactivateForum" asp-route-forumId="@Model.Id" asp-route-page="@Model.CurrentPage">Deactivate Forum</a>
        </div>
    </div>
    <hr />
}
<table class="table table-bordered table-hover">
    <thead class="bg-primary">
        <tr>
            <th>
                <h2 align="center">@Model.Name</h2>
            </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var message in Model.Messages)
        {
            <tr>
                <td>
                    @if (message.CommenterUsername == this.User.Identity.Name && Model.IsActive)
                    {
                        <div class="row">
                            <div class="col-sm-12">
                                <a align="left" class="btn btn-primary" asp-area="Information" asp-controller="ForumMessages" asp-action="Edit" asp-route-forumMessageId="@message.Id" asp-route-page="@Model.CurrentPage">Edit</a>
                            </div>
                        </div>
                    }
                    <div class="row">
                        <div class="col-sm-12">
                            <h4 align="center">@message.Message</h4>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <a align="left" asp-area="Identity" asp-controller="Users" asp-action="UserProfile" asp-route-username="@message.CommenterUsername"><h6>@message.CommenterUsername</h6></a>
                            <h6 align="left">Updated at: @message.UpdateDate</h6>
                            <h6 align="left">Created at: @message.CreationDate</h6>
                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

@if (Model.IsActive)
{
    @Html.ValidationSummary()

    <form asp-area="Information" asp-controller="ForumMessages" asp-action="Create" method="post">
        <input type="hidden" asp-for="Id">
        <input type="hidden" asp-for="IsActive">
        <input type="hidden" asp-for="MinPage">
        <input type="hidden" asp-for="MaxPage">
        <input type="hidden" asp-for="CurrentPage">
        <input type="hidden" asp-for="Name">
        <input type="hidden" asp-for="Messages">
        <input type="hidden" asp-for="CreationDate">
        <input type="hidden" asp-for="UpdateDate">
        <input type="hidden" asp-for="CreatorUsername">
        <div class="row form-group">
            <div class="col-sm-12">
                <textarea class="form-control" rows="5" placeholder="Comment" asp-for="NewComment"></textarea>
            </div>
        </div>
        <div class="row form-group">
            <div class="col-sm-3">
                <input class="form-control btn-primary" type="submit" value="Post Comment" />
            </div>
        </div>

    </form>
}
else
{
    <p class="text-primary" align="center">This topic is closed.</p>
}

<div class="center-text">
        @for (int i = Model.MinPage; i < Model.MaxPage; i++)
        {
            <a class="btn btn-primary margin-top-10" asp-area="Information" asp-controller="Forums" asp-action="Forum" asp-route-page="@i" asp-route-id="@Model.Id">@i</a>
        }
</div>

LearnSoftware/Areas/Information/Views/Forums/Index.cshtml
@using LearnSoftware.ViewModels.ForumCategories
@model ForumCategoryIndexViewModel

@{
    ViewData["Title"] = Model.ForumCategoryName;
}
<hr />
<div class="row">
    <form asp-area="Information" asp-controller="Forums" asp-action="Index" method="Get">
        <div class="col-sm-3 form-group">
            <input placeholder="Search..." class="form-control" type="text" name="search" />
            <input type="hidden" name="forumCategoryId" value="@Model.Id" />
            <input type="hidden" name="page" value="@Model.CurrentPage" />
        </div>
        <div class="col-sm-2 form-group">
            <input class="form-control btn-primary" type="submit" value="Search">
        </div>
    </form>
    <div class="col-sm-offset-5 col-sm-2 form-group">
        <a align="center" class="form-control btn-primary" asp-area="Information" asp-controller="Forums" asp-action="Create" asp-route-forumCategoryId="@Model.Id">Create Forum</a>
    </div>
</div>
<table class="table table-bordered table-hover">
    <thead class="bg-primary">
        <tr>
            <th>
                <div class="truncate-large center-items">
                    <h2 align="center">@Model.ForumCategoryName</h2>
                </div>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var forum in Model.Forums)
        {
            <tr>
                <td>
                    
                    <a align="center" asp-area="Information" asp-controller="Forums" asp-action="Forum" asp-route-id="@forum.Id"><h3>@forum.Name</h3></a>
                    <p align="center">Created by: <a align="center" asp-area="Identity" asp-controller="Users" asp-action="UserProfile" asp-route-username="@forum.CreatorUsername">@forum.CreatorUsername</a></p>
                    <p align="center">Created on: @forum.CreatedOn</p>
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="center-text">
    @for (int i = Model.MinPage; i < Model.MaxPage; i++)
    {
        <a class="margin-top-10 btn btn-primary" asp-area="Information" asp-controller="Forums" asp-action="Index" asp-route-forumCategoryId="@Model.Id" asp-route-search="@Model.Search" asp-route-page="@i">@i</a>
    }
</div>