LearnSoftware/Areas/Learn/Controllers/LecturesController.cs
using System.Linq;
using LearnSoftware.Areas.Identity.Data;
using LearnSoftware.ViewModels.Lectures;
using LearnSoftware.Controllers;
using LearnSoftware.Models;
using LearnSoftware.Models.Learn;
using LearnSoftware.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using LearnSoftware.Services.Interfaces;
using System;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace LearnSoftware.Areas.Learn.Controllers
{
    [Area("Learn")]
    public class LecturesController : Controller
    {
        private ICourseService courseService;
        private ILectureService lectureService;
        private ISubscriptionService subscriptionService;
        private UserManager<LSIdentityUser> userManager;

        public LecturesController(ICourseService courseService, ILectureService lectureService, ISubscriptionService subscriptionService, UserManager<LSIdentityUser> userManager)
        {
            this.courseService = courseService;
            this.lectureService = lectureService;
            this.subscriptionService = subscriptionService;
            this.userManager = userManager;
        }


        // GET: /<controller>/
        [Authorize]
        public IActionResult Lecture(int id)
        {
            var lecture = lectureService.GetLecture((int)id);

            if(lecture == null)
            {
                this.NotFound();
            }

            if (!lecture.IsCourseActive && !this.User.IsInRole("Admin"))
            {
                return this.Unauthorized();
            }

            ViewData["IsUserSubscribed"] = subscriptionService.IsUserSubscribed(this.User.Identity.Name, lecture.CourseId);

            LectureLectureViewModel model = new LectureLectureViewModel()
            {
                Id = lecture.Id,
                Name = lecture.Name,
                CourseType = lecture.Course.CourseType,
                LectureTextExplnation = lecture.LectureTextExplnation,
                LectureVideoUrl = lecture.LectureVideoUrl,
                CourseId = lecture.CourseId,
                Exercises = lecture.Exercices.Select(e => new LectureExerciseViewModel()
                {
                    Id = e.Id,
                    Name = e.Name,
                }).ToList()
            };

            var user = userManager.FindByNameAsync(this.User.Identity.Name).Result;

            if (user == null || lecture?.Course == null)
            {
                return this.NotFound();
            }

            if (!courseService.HasUserCourse(user.Id, lecture.Course.Id)
                && (courseService.IsCourseFree(lecture.Course.Id) 
                || courseService.IsCoursePurchased(lecture.Course.Id, user.Id)))
            {
                courseService.CreateUserCourse(lecture.Course, user);
            }

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet("/Lectures/Edit/{lectureId}")]
        public IActionResult Edit(int lectureId)
        {
            var lecture = lectureService.GetLecture(lectureId);

            if (lecture == null)
            {
                return this.NotFound();
            }

            LectureCreateViewModel model = new LectureCreateViewModel()
            {
                Id = lectureId,
                Name = lecture.Name,
                LectureTextExplnation = lecture.LectureTextExplnation,
                LectureVideoUrl = lecture.LectureVideoUrl,
                LectureVideoLengthInMinutes = (int)Math.Floor(new TimeSpan(lecture.VideoLength).TotalMinutes)
            };

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost("/Lectures/Edit/{lectureId}")]
        public IActionResult Edit(LectureCreateViewModel model)
        {
            if(!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var lecture = lectureService.GetLecture(model.Id);

            if(lecture == null)
            {
                return this.NotFound();
            }

            lectureService.UpdateLecture(lecture, model.LectureTextExplnation, model.LectureVideoUrl, model.Name, model.LectureVideoLengthInMinutes);

            return this.RedirectToAction("Lecture", "Lectures", new { id = model.Id });
        }

        [Authorize(Roles = "Admin")]
        [HttpGet("/Lectures/Create/{courseId}")]
        public IActionResult Create(int courseId)
        {
            var courseExists = courseService.HasCourse((int)courseId);

            if (!courseExists)
            {
                return this.NotFound();
            }

            LectureCreateViewModel model = new LectureCreateViewModel() { Id = (int)courseId };

            return View(model);
        }

        [HttpPost("/Lectures/Create/{courseId}")]
        [Authorize(Roles = "Admin")]
        public IActionResult Create(LectureCreateViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return View(model);
            }

            Course course = courseService.GetCourse(model.Id);

            if(course == null)
            {
                return this.BadRequest();
            }

            int lectureId = lectureService.CreateLecture(course, model.LectureTextExplnation, model.LectureVideoUrl, model.Name, model.LectureVideoLengthInMinutes);

            return RedirectToAction("Lecture","Lectures", new { id = lectureId });
        }
    }
}

LearnSoftware/Areas/Payment/Controllers/SubscriptionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Braintree;
using LearnSoftware.Services;
using LearnSoftware.Services.Interfaces;
using LearnSoftware.ViewModels.Subscriptions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace LearnSoftware.Areas.Payment.Controllers
{
    [Authorize]
    [Area("Payment")]
    public class SubscriptionController : Controller
    {
        private ISubscriptionService subscriptionService;
        private ICourseService courseService;
        private LSIdentityUserManager lSIdentityUserManager;

        public SubscriptionController(ISubscriptionService subscriptionService, ICourseService courseService, LSIdentityUserManager lSIdentityUserManager)
        {
            this.subscriptionService = subscriptionService;
            this.courseService = courseService;
            this.lSIdentityUserManager = lSIdentityUserManager;
        }

        [HttpGet]
        public IActionResult GenerateToken()
        {
            string token = subscriptionService.GenerateToken();
            return Json(token);
        }

        [HttpGet]
        public IActionResult PurchaseCourse(int id)
        {
            if(subscriptionService.IsUserSubscribed(User.Identity.Name, id))
            {
                return RedirectToAction("Course", "Courses", new { area = "Learn", id = id });
            }

            if (!courseService.HasCourse(id))
            {
                return NotFound();
            }

            var model = subscriptionService.GetCoursePrePaymentData(id, User.Identity.Name);

            return View(model);
        }

        [HttpPost]
        public IActionResult PurchaseCourse(SubscirptionPaymentViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            if (!courseService.HasCourse(model.course_id))
            {
                return NotFound();
            }

            if (courseService.IsCourseFree(model.course_id))
            {
                return BadRequest();
            }

            var response = subscriptionService.GetCoursePrePaymentData(model.course_id, User.Identity.Name);
            var user = lSIdentityUserManager.FindByNameAsync(User.Identity.Name).Result;
            if (user == null || !lSIdentityUserManager.IsEmailConfirmedAsync(user).Result)
            {
                return View(response);
            }

            var paymentResponse = subscriptionService.MakePayment(model, User.Identity.Name);
            response.TransactionId = paymentResponse.TransactionId;
            response.Message = paymentResponse.ErrorMessage;

            return View(response);
        }
    }
}

LearnSoftware/Areas/Learn/Views/Lectures/Create.cshtml
@{
    ViewData["Title"] = "Create Lecture";
}

@using LearnSoftware.ViewModels.Lectures
@model LectureCreateViewModel
<div class="row">
    <div class="col-sm-offset-3 col-sm-6 form-group">
        @Html.ValidationSummary()
    </div>
</div>
<form asp-area="Learn" asp-controller="Lectures" asp-action="Create" method="post">
    <partial name="_CreateEditFieldsLecturesPartialView" />
    <div class="row">
        <div class="col-sm-offset-3 col-sm-6 form-group">
            <input class="form-control btn-primary" type="submit" value="Create" />
        </div>
    </div>
</form>

LearnSoftware/Areas/Learn/Views/Lectures/Edit.cshtml
@{
    ViewData["Title"] = "Edit Lecture";
}

@using LearnSoftware.ViewModels.Lectures
@model LectureCreateViewModel

<div class="row">
    <div class="col-sm-offset-3 col-sm-6 form-group">
        @Html.ValidationSummary()
    </div>
</div>

<form asp-area="Learn" asp-controller="Lectures" asp-action="Edit" method="post">
    <partial name="_CreateEditFieldsLecturesPartialView" />
    <div class="row">
        <div class="col-sm-offset-3 col-sm-6 form-group">
            <input class="form-control btn-primary" type="submit" value="Edit" />
        </div>
    </div>
</form>

LearnSoftware/Areas/Learn/Views/Lectures/Lecture.cshtml
@{
    ViewData["Title"] = "Lecture";
    bool isUserSubscribed = (bool)ViewData["IsUserSubscribed"];
}

@using LearnSoftware.ViewModels.Lectures
@model LectureLectureViewModel
<hr />
@if (this.User.IsInRole("Admin"))
{
    <div class="row">
        <div class="form group col-sm-offset-4 col-sm-2">
            <a align="center" class="form-control btn-primary" asp-area="Learn" asp-controller="Exercises" asp-action="Create" asp-route-lectureId="@Model.Id">Create Exercise</a>
        </div>
        <div class="form-group col-sm-2">
            <a align="center" class="form-control btn-primary" asp-area="Learn" asp-controller="Lectures" asp-action="Edit" asp-route-lectureId="@Model.Id">Edit Lecture</a>
        </div>
    </div>
}
<div class="truncate-large center-items center-text">
    <h2 align="center" class="text-primary">@Model.Name</h2>
</div>
<hr />
<div class="row">
    @if (Model.CourseType != CourseType.Free && !isUserSubscribed && !this.User.IsInRole("Admin"))
    {
    <div class="row">
        <div class="col-sm-offset-3 col-sm-6 form-group">
            <h4 align="center" class="text-primary">You need to purchase the course to view this lecture</h4>
            <a align="center" class="form-control btn-primary" asp-area="Payment" asp-controller="Subscription" asp-action="PurchaseCourse" asp-route-id="@Model.CourseId">Purchase Course</a>
        </div>
    </div>
    }
    else
    {
        <div class="col-sm-3">
            <table class="table table-bordered table-hover">
                <thead class="bg-primary">
                    <tr>
                        <th>
                            <div class="truncate-large center-items">
                                <h5 align="center">Exercises</h5>
                            </div>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var exercise in Model.Exercises)
                    {
                        <tr>
                            <td>
                                <div class="truncate center-items">
                                    <h5 class="truncate-text center-text" align="center"><a asp-area="Learn" asp-controller="Exercises" asp-action="Exercise" asp-route-id="@exercise.Id">@exercise.Name</a></h5>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="col-sm-9">
            @if (!String.IsNullOrEmpty(Model.LectureVideoUrl))
            {
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="@Model.LectureVideoUrl" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
                <hr />
            }

            <h3 align="center" class="text-primary">Description:</h3>
            <div class="truncate-large-100 center-items center-text">
                <h4 align="center" class="text-primary">@Model.LectureTextExplnation</h4>
            </div>
        </div>
    }
</div>


LearnSoftware/Areas/Learn/Views/Lectures/_CreateEditFieldsLecturesPartialView.cshtml
@using LearnSoftware.ViewModels.Lectures
@model LectureCreateViewModel

<input type="hidden" asp-for="Id">
<div class="row">
    <div class="col-sm-offset-3 col-sm-6 form-group">
        <label class="text-primary" for="Name">Lecture Name</label>
        <input class="form-control" placeholder="Lecture Name" type="text" asp-for="Name">
    </div>
</div>
<div class="row">
    <div class="col-sm-offset-3 col-sm-6 form-group">
        <label class="text-primary" for="LectureVideoUrl">Video Url</label>
        <input class="form-control" placeholder="Lecture Video Url" type="text" asp-for="LectureVideoUrl">
    </div>
</div>

<div class="row">
    <div class="col-sm-offset-3 col-sm-6 form-group">
        <label class="text-primary" for="LectureVideoLengthInMinutes">Video Lengh In Minutes</label>
        <input class="form-control" placeholder="Lecture Video Url" type="number" asp-for="LectureVideoLengthInMinutes">
    </div>
</div>

<div class="row">
    <div class="col-sm-offset-3 col-sm-6 form-group">
        <label class="text-primary" for="LectureTextExplnation">Text Explanation</label>
        <textarea class="form-control" rows="7" placeholder="Lecture Text Explnation" type="text" asp-for="LectureTextExplnation"></textarea>
    </div>
</div>